# Ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
  - method: pip
    path: .
  - requirements: requirements.txt
  - requirements: requirements-doc.txt
  - requirements: requirements-encrypt.txt
  - requirements: requirements-furo-sphinx-search.txt
